
testAbleToWorkWithCustomExceptions=true
testExceptionIsThrownAndHandledIfShopIdIsNotValidWhileGettingNoteById=true
testDataValidationCheckIsAddedInController=true
testExceptionIsThrownAndHandledIfShopIdIsNotValidWhileDeleting=true
testExceptionIsThrownAndHandledInCaseOfInvalidData=true
testUserExceptionIsThrownAndHandledIfUserIdIsNotValidWhileGettingNoteById=true
testUserDataValidationCheckIsAddedInController=true
testUserExceptionIsThrownAndHandledIfUserIdIsNotValidWhileDeleting=true